### ISSUE TITLE
Make volunteer pages look good

### ISSUE THREAD

**Issue by jpaav** [CHSCodeForChange/Sapphire-web#10]
They are ugly. As usual, don't make design calls without consulting the whole frontend team. This consists of editing all the django templates (stored as .html files) found under 'resources/volunteer/'

**Comment by armaangoel78** [comment]
What does good first issue mean

**Comment by jpaav** [comment]
It means that it is a good place for people to start that doesn't require in depth knowledge of the existing code.

**Comment by armaangoel78** [comment]
Also need to use Bootstrap and Django templates
