### ISSUE TITLE
"SMTP Authentication Error"

### ISSUE THREAD

**Issue by armaangoel78** [CHSCodeForChange/Sapphire-web#11]
Error whenever I try to sign up, see attached image
![image](https://user-images.githubusercontent.com/13454847/33002244-f4f7ff86-cd80-11e7-92b2-04b78b53738b.png)

**Comment by jpaav** [comment]
This is likely because the either you did not change the email password in settings.py since you pulled or you changed the email to 2-factor auth which breaks this feature.

**Comment by armaangoel78** [comment]
probably the former, thanks
