### ISSUE TITLE
Bell icon mobile placement

### ISSUE THREAD

**Issue by jpaav** [CHSCodeForChange/Sapphire-Web#130]
The bell icon goes down to bottom of collapse menu when it is expanded on mobile. Ideally it would stay to the top right instead of being moved to the bottom of the collapse menu.

**Comment by armaangoel78** [comment]
I think you fixed this

**Comment by armaangoel78** [comment]
But its really jank

**Comment by armaangoel78** [comment]
I would just use some jquery to make it go immediately to the feed page rather than showing the dropdown when in mobile
