### ISSUE TITLE
Email Registration form

### ISSUE THREAD

**Issue by jpaav** [CHSCodeForChange/Sapphire-web#3]
This email template looks like trash. We need to update the way it looks. This will require knowledge of Django Templates as well as html. It will also require basic knowledge of the backend framework if you want to include other fields (ie besides the user's name). If you are confused don't hesitate to ask a backend dev. **Make sure to discuss design with other Frontend Web Devs before designing this.** This website should look good and that means it will need unity and a common design, even in the email template. See #1 & #2

**Comment by armaangoel78** [comment]
See google drive folder that is shared with you (only shared to Andrew and Joe so far, see Discord).
