### ISSUE TITLE
Anyone can edit any bio

### ISSUE THREAD

**Issue by armaangoel78** [CHSCodeForChange/Sapphire-web#33]
see title. This is a big problem and it brings into question other security flaws. We need to spend some quality time making sure that there are no holes in our system.

**Comment by armaangoel78** [comment]
BTW to edit another profiles bio you just change the id in the url to their profile's id

**Comment by jpaav** [comment]
The easiest fix for this is to compare the profile and the user in the template 
```
{% if request.user==profile.user %}
//Code to show edit buttons
{% endif %}
```
PS that's pseudo code im not sure about the profile.user bit that probably won't work
