### ISSUE TITLE
Use permission tags instead of passing in is_organizer

### ISSUE THREAD

**Issue by jpaav** [CHSCodeForChange/Sapphire-web#35]
permission tags are made for this sort of thing. Specifically in volunteer/views with functions event and slot but there may be more.

**Comment by armaangoel78** [comment]
Remember that groups broke the permissions tag idea since they have to be dynamic, that is why we pass is organizer. We may be able to move back to permission tags as Jared found a way to do so, but for now the way we do it works.

**Comment by armaangoel78** [comment]
If you are curious the new we do it is by storing a list of volunteers and organizers in the group model. To check if they are an organizer or volunteer there is a function in the model that sees if the user is on the list.

**Comment by jpaav** [comment]
Yeah I think that moving back to permission tags wouldn't be too much of a hassle. Its up to you if you think its worth it I can do it now.

**Comment by jpaav** [comment]
Currently not worth the trouble since it offers only small performance difference if any.
