### ISSUE TITLE
Add template for email confirmation

### ISSUE THREAD

**Issue by jpaav** [CHSCodeForChange/Sapphire-web#6]
Currently we only use a text HttpResponse which isn't pretty or useful. Make sure to allow the user to return to login page from email confirmation page. The suggestions on designing this are like the rest of the site. **Communicate on design** so the site doesn't look like a template picker on a drag and drop website builder. Put this in resources/templates/accounts/confirmation.html

**Comment by Danp1140** [comment]
*Quick Note For Fix: html of e-mail is stored in resources/templates/emails/activate_account.html, NOT resources/templates/accounts/confirmation.html
